spring:
  application:
    name: springboot-multiple-datasource

  sql:
    init:
      mode: always

  mysql:
    datasource:
      url: jdbc:mysql://localhost:3306/sb_mds_demo
      username: admin
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
  
  pg:
    datasource:
      url: jdbc:postgresql://localhost:5432/sb_mds_demo
      username: admin
      password: admin
      driver-class-name: org.postgresql.Driver
  
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false

    hibernate:
      ddl-auto: update
      
    properties:
      '[hibernate.format_sql]': true
